"""empty message

Revision ID: 0d03c288ab28
Revises: adc3f6b6aca8
Create Date: 2025-12-04 21:30:44.729741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from enums.language import Language

# revision identifiers, used by Alembic.
revision: str = '0d03c288ab28'
down_revision: Union[str, None] = 'adc3f6b6aca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language",
                            sa.Enum('EN', 'FR', 'DE', 'IT', name='language'),
                                      server_default=Language.EN.name,
                                      default=Language.EN,
                                      nullable=False))
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
