"""empty message

Revision ID: 1555220764ee
Revises: 
Create Date: 2025-11-17 18:39:44.422629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1555220764ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    with open("static/no_image.jpeg", "r") as f:
        bot_photo_id = f"0{f.read()}"
        op.add_column('categories', sa.Column('photo_id', sa.String(), nullable=True))
        op.add_column('subcategories', sa.Column('photo_id', sa.String(), nullable=True))
    op.execute(f"""
        UPDATE categories SET photo_id='0{bot_photo_id}'; 
    """)
    op.execute(f"""
        UPDATE subcategories SET photo_id='0{bot_photo_id}'; 
    """)
    with op.batch_alter_table('categories') as batch_op:
        batch_op.alter_column('photo_id', nullable=False)
    with op.batch_alter_table('subcategories') as batch_op:
        batch_op.alter_column('photo_id', nullable=False)
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategories', 'photo_id')
    op.drop_column('categories', 'photo_id')
    # ### end Alembic commands ###
