"""empty message

Revision ID: 27f5d125998d
Revises: b95c96643b23
Create Date: 2025-12-17 00:56:30.988837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f5d125998d'
down_revision: Union[str, None] = 'b95c96643b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_banned",
                                      sa.Boolean,
                                      nullable=False,
                                      default=False,
                                      server_default="false"))
        batch_op.alter_column("language", nullable=False)
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
