"""empty message

Revision ID: 3cf73b7c4507
Revises: d14008036574
Create Date: 2025-12-24 00:18:46.837257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3cf73b7c4507'
down_revision: Union[str, None] = 'd14008036574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "buyItem_id",
            sa.Integer(),
            sa.ForeignKey("buyItem.id", ondelete="CASCADE"),
            nullable=False,
            unique=True
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("image_id", sa.String(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("create_datetime", sa.DateTime(timezone=True), nullable=False),

        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5",
            name="check_review_rating_value",
        ),
        sa.CheckConstraint(
            "length(text) <= 512",
            name="check_review_text_length",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
