"""empty message

Revision ID: 43803f266c4a
Revises: 3cf73b7c4507
Create Date: 2026-01-11 15:56:13.373754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '43803f266c4a'
down_revision: Union[str, None] = '3cf73b7c4507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('referred_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name="fk_users_referred_by_user_id",
            referent_table="users",
            local_cols=['referred_by_user_id'],
            remote_cols=['id'],
        )
        batch_op.create_check_constraint("check_no_self_referral", "referred_by_user_id != id")
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)

    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fiat_amount", sa.Float(), nullable=True))

    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.execute("UPDATE deposits SET fiat_amount=0.0;")
        batch_op.create_check_constraint("check_fiat_amount", "fiat_amount >= 0")
        batch_op.alter_column("fiat_amount", nullable=False)

    op.create_table('referral_bonus',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('referral_user_id', sa.Integer(), nullable=False),
                    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
                    sa.Column('payment_amount', sa.Float(), nullable=False),
                    sa.Column('applied_referral_bonus', sa.Float(), nullable=False),
                    sa.Column('applied_referrer_bonus', sa.Float(), nullable=False),
                    sa.CheckConstraint('referral_user_id != referrer_user_id', name='check_no_self_referral'),
                    sa.ForeignKeyConstraint(['referral_user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
