"""empty message

Revision ID: 547834cf4d64
Revises: 1555220764ee
Create Date: 2025-11-19 20:10:40.604459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547834cf4d64'
down_revision: Union[str, None] = '1555220764ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('button', sa.Enum('ALL_CATEGORIES', 'MY_PROFILE', 'FAQ', 'HELP', 'CART', name='keyboardbutton'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('button'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons_media')
    # ### end Alembic commands ###
