"""empty message

Revision ID: 56e532f7e9ff
Revises: 
Create Date: 2025-06-16 13:47:58.793919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e532f7e9ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processing_payment_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('expire_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('deposits', 'vout')
    op.drop_column('deposits', 'tx_id')
    op.drop_column('deposits', 'token_name')
    op.drop_column('deposits', 'is_withdrawn')
    op.drop_column('users', 'seed')
    op.drop_column('users', 'btc_balance')
    op.drop_column('users', 'usdc_erc20_balance')
    op.drop_column('users', 'btc_address')
    op.drop_column('users', 'eth_address')
    op.drop_column('users', 'ltc_address')
    op.drop_column('users', 'ltc_balance')
    op.drop_column('users', 'last_balance_refresh')
    op.drop_column('users', 'usdt_trc20_balance')
    op.drop_column('users', 'sol_address')
    op.drop_column('users', 'usdt_erc20_balance')
    op.drop_column('users', 'trx_address')
    op.drop_column('users', 'sol_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sol_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('trx_address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('usdt_erc20_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('sol_address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('usdt_trc20_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('last_balance_refresh', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('ltc_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('ltc_address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('eth_address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('btc_address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('usdc_erc20_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('btc_balance', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('seed', sa.VARCHAR(), nullable=False))
    op.add_column('deposits', sa.Column('is_withdrawn', sa.BOOLEAN(), nullable=True))
    op.add_column('deposits', sa.Column('token_name', sa.VARCHAR(), nullable=True))
    op.add_column('deposits', sa.Column('tx_id', sa.VARCHAR(), nullable=False))
    op.add_column('deposits', sa.Column('vout', sa.INTEGER(), nullable=True))
    op.drop_table('payments')
    # ### end Alembic commands ###
