"""empty message

Revision ID: b95c96643b23
Revises: 0d03c288ab28
Create Date: 2025-12-08 21:46:03.201008

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'b95c96643b23'
down_revision: Union[str, None] = '0d03c288ab28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")

    with op.batch_alter_table('buys') as batch_op:
        batch_op.drop_column("quantity")

    with op.batch_alter_table("buyItem") as batch_op:
        batch_op.add_column(sa.Column("item_ids", sa.JSON(), nullable=True))

    conn = op.get_bind()

    rows = conn.execute(sa.text("""
        SELECT buy_id, item_id
        FROM buyItem
        ORDER BY buy_id
    """)).fetchall()

    grouped = {}
    for buy_id, item_id in rows:
        grouped.setdefault(buy_id, []).append(item_id)

    for buy_id, item_ids in grouped.items():
        conn.execute(
            sa.text("""
                UPDATE buyItem
                SET item_ids = :item_ids
                WHERE buy_id = :buy_id
            """),
            {
                "item_ids": json.dumps(item_ids),
                "buy_id": buy_id,
            },
        )

    conn.execute(sa.text("""
        DELETE FROM buyItem
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM buyItem
            GROUP BY buy_id
        )
    """))

    with op.batch_alter_table("buyItem") as batch_op:
        batch_op.drop_column("item_id")

    with op.batch_alter_table("buyItem") as batch_op:
        batch_op.alter_column("item_ids", nullable=False)

    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
