"""empty message

Revision ID: b95c96643b23
Revises: 0d03c288ab28
Create Date: 2025-12-08 21:46:03.201008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'b95c96643b23'
down_revision: Union[str, None] = '0d03c288ab28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    bind = op.get_bind()
    with op.batch_alter_table('buyItem') as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    bind.execute(text("""
            UPDATE "buyItem"
            SET quantity = (SELECT quantity FROM buys WHERE id = "buyItem".buy_id)
        """))

    with op.batch_alter_table('buyItem') as batch_op:
        batch_op.alter_column('quantity', nullable=False)
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    bind = op.get_bind()
    with op.batch_alter_table('buys') as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    bind.execute(text("""
            UPDATE buys
            SET quantity = (SELECT quantity FROM "buyItem" WHERE buy_id = buys.id)
        """))

    with op.batch_alter_table('buys') as batch_op:
        batch_op.alter_column('quantity', nullable=False)

    with op.batch_alter_table('buyItem') as batch_op:
        batch_op.drop_column('quantity')
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###
