"""empty message

Revision ID: f4a4986cc57f
Revises: 27f5d125998d
Create Date: 2025-12-17 15:17:38.295655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a4986cc57f'
down_revision: Union[str, None] = '27f5d125998d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=0;")
    with op.batch_alter_table("coupons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name",
                                      sa.String,
                                      nullable=True))
        batch_op.create_unique_constraint("coupons_name_unique", "name")

    with op.batch_alter_table("buys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discount",
                                      sa.Float,
                                      nullable=False,
                                      default=0.0,
                                      server_default="0.0"))
    op.execute("PRAGMA foreign_keys=1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
